### ISSUE TITLE
Adicionar  requirements para o projeto

### ISSUE THREAD

**Issue by PedroRegisPOAR** [AllanRPereira/OrGaNi#1]
Para facilitar que outras pessoas possam contribuir adicione um arquivo de requerimentos do projeto com o nome padrão requirements.txt para o projeto para facilitar que outras pessoas possam contribuir com muito mais facilidade.

Basta fazer pip freeze > requirements.txt

Mais explicações sobre o que é o requirements e sobre o pip freeze > requirements.txt, no link:
https://pip.pypa.io/en/stable/user_guide/

**Comment by AllanRPereira** [comment]
Requerimentos já adicionados!
